import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  welcomeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5E9',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginBottom: 14,
    alignSelf: 'center',
  },
  welcomeBadgeText: {
    color: '#0F613B',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 6,
    letterSpacing: 0.5,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2D3748',
    textAlign: 'center',
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 20,
    lineHeight: 20,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#4A5568',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1F2937',
  },
  inputDisabled: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  inputDisabledText: {
    color: '#6B7280',
    fontWeight: '600',
  },
  passwordInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 14,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1F2937',
  },
  eyeIconButton: {
    padding: 6,
  },
  requirementsBox: {
    backgroundColor: '#F8FAF9',
    borderRadius: 12,
    padding: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  requirementsTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#4A5568',
    marginBottom: 8,
  },
  reqRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  reqText: {
    fontSize: 12,
    color: '#64748B',
    marginLeft: 6,
  },
  reqTextActive: {
    color: '#0F613B',
    fontWeight: '600',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    borderRadius: 4,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxChecked: {
    backgroundColor: '#0F613B',
    borderColor: '#0F613B',
  },
  rememberText: {
    fontSize: 13.5,
    color: '#64748B',
    fontWeight: '500',
  },
  submitButton: {
    backgroundColor: '#0F613B',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 14,
    shadowColor: '#0F613B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelLink: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  cancelLinkText: {
    fontSize: 13.5,
    color: '#64748B',
    fontWeight: '600',
  },
  bottomLinksRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: '#9FB8AA',
    shadowOpacity: 0.05,
    elevation: 0,
  },
  termsAgreementBox: {
    backgroundColor: '#F2F8F4',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#D3E6DC',
  },
  termsCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  termsCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#0F613B',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 2,
  },
  termsCheckboxChecked: {
    backgroundColor: '#0F613B',
    borderColor: '#0F613B',
  },
  termsTextContainer: {
    flex: 1,
  },
  termsAgreementText: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 18,
  },
  termsLinkText: {
    color: '#0F613B',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  termsInfoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#DEEBE3',
  },
  termsInfoButtonText: {
    fontSize: 12,
    color: '#0F613B',
    fontWeight: '600',
  },
  forgotPasswordText: {
    fontSize: 13.5,
    color: '#0E5C3A',
    fontWeight: '600',
    textAlign: 'center',
  },
  codeInputWrapper: {
    backgroundColor: '#F0FDF4',
    borderWidth: 2,
    borderColor: '#168A54',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  codeInput: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 12,
    color: '#0F613B',
    textAlign: 'center',
    width: '100%',
    paddingVertical: 4,
  },
  codeHelperText: {
    fontSize: 12.5,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 18,
  },
  resendRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  resendPromptText: {
    fontSize: 13,
    color: '#6B7280',
  },
  resendLinkText: {
    fontSize: 13,
    color: '#0F613B',
    fontWeight: '700',
    textDecorationLine: 'underline',
    marginLeft: 4,
  },
  modifyEmailLink: {
    alignItems: 'center',
    marginBottom: 12,
  },
  modifyEmailText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
});
